version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - FRONTEND_URL=http://frontend:3000
      - CORS_ORIGIN=http://frontend:3000
      - DATABASE_URL=postgresql://postgres.scxhouqvgpeospjdfudr:@aws-0-us-west-1.pooler.supabase.com:5432/postgres

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5001
    depends_on:
      - backend
